version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/alphasoc/flightsim
    steps:
      - checkout
      - run: go install -mod vendor -v ./...
      - run: go test -mod vendor -race -v ./...
      - run:
          name: build
          command: |
            GOARCH=amd64 GOOS=windows go build -mod vendor -o flightsim-windows-amd64.exe -ldflags "-X main.Version=$(git describe)"
            GOARCH=amd64 GOOS=linux   go build -mod vendor -o flightsim-linux-amd64       -ldflags "-X main.Version=$(git describe)"
            GOARCH=amd64 GOOS=darwin  go build -mod vendor -o flightsim-darwin-amd64      -ldflags "-X main.Version=$(git describe)"
      - persist_to_workspace:
          root: .
          paths:
            - flightsim-windows-amd64.exe
            - flightsim-linux-amd64
            - flightsim-darwin-amd64
  # lint:
  #   docker:
  #     - image: circleci/golang:1.13
  #   working_directory: /go/src/github.com/alphasoc/flightsim
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: gometalinter-tools-{{ checksum "/go/bin/gometalinter" }}
  #     - run: go get github.com/alecthomas/gometalinter
  #     - run: gometalinter --install
  #     - save_cache:
  #         key: gometalinter-tools-{{ checksum "/go/bin/gometalinter" }}
  #         paths:
  #           - /go/bin/
  #     - run: go install ./...
  #     - run:
  #         name: run linters
  #         command:  |
  #           gometalinter        \
  #           --vendor            \
  #           --disable-all       \
  #           --enable=gofmt      \
  #           --enable=golint     \
  #           --enable=goimports  \
  #           --enable=vetshadow  \
  #           --enable=misspell   \
  #           --enable=vet ./...

  publish:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/alphasoc/flightsim
    steps:
      - attach_workspace:
          at: .
      - run:
          name: publish
          command: |
            go get github.com/aktau/github-release
            github-release release --draft --user alphasoc --repo flightsim --tag $CIRCLE_TAG
            github-release upload  --user alphasoc --repo flightsim --tag $CIRCLE_TAG --name flightsim-windows-amd64.exe --file flightsim-windows-amd64.exe
            github-release upload  --user alphasoc --repo flightsim --tag $CIRCLE_TAG --name flightsim-linux-amd64 --file flightsim-linux-amd64
            github-release upload  --user alphasoc --repo flightsim --tag $CIRCLE_TAG --name flightsim-darwin-amd64 --file flightsim-darwin-amd64

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9]+[.].*$/
      # - lint:
      #     filters:
      #       tags:
      #         only: /^v[0-9]+[.].*$/
      - publish:
          context: github-alphasoc-deploy
          requires:
            - build
            # - lint
          filters:
            tags:
              only: /^v[0-9]+[.].*$/
            branches:
              ignore: /.*/
